version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: hrms-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - hrms-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hrms-backend
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - DATABASE_NAME=hrms_lite
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - mongodb
    networks:
      - hrms-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hrms-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - hrms-network

volumes:
  mongodb_data:

networks:
  hrms-network:
    driver: bridge
